version: "3.7"

services:

  fastapi-file-server:
    image: python:3.9.5
    container_name: fastapi-file-server
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ALL_PROXY: "http://host.docker.internal:7890"
    volumes:
      - .:/opt/fastapi-file-server
    ports:
      - 30080:30080
    command: tail -f /dev/null 
